{
 "title": "Hitron Router",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_info_uptime" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_login_success_bool", "legendFormat": "Login" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_address" }
   ]
  },
  {
   "title": "MAC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_address" }
   ]
  },
  {
   "title": "Hardware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_version" }
   ]
  },
  {
   "title": "Software",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_version" }
   ]
  },
  {
   "title": "BPI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_cm_bpi_status", "legendFormat": "auth: {{auth}} tek: {{tek}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hitron_scrape_time{component=\"all\"}",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_address" }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_version" }
   ]
  },
  {
   "title": "CM Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hitron_cm_hwinit_success", "legendFormat": "HWInit" },
    {
     "expr": "hitron_cm_find_downstream_success",
     "legendFormat": "Lock DS"
    },
    { "expr": "hitron_cm_ranging_success", "legendFormat": "Ranging" },
    { "expr": "hitron_cm_dhcp_success", "legendFormat": "DHCP" },
    {
     "expr": "hitron_cm_download_config_success",
     "legendFormat": "Config DL"
    },
    { "expr": "hitron_cm_registration_success", "legendFormat": "Registration" }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    { "expr": "rate(hitron_traffic)", "legendFormat": "{{if}} {{dir}}" }
   ]
  },
  {
   "title": "Devices online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hitron_lan_device) by (ip_type)",
     "legendFormat": "{{ip_type}}"
    }
   ]
  },
  {
   "title": "Devices online",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 12 },
   "targets": [
    { "expr": "hitron_lan_device" }
   ]
  },
  {
   "title": "Scrape Time by Section",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hitron_scrape_time{component != \"all\"}",
     "legendFormat": "{{component}}"
    },
    {
     "expr": "hitron_scrape_time{component = \"all\"}",
     "legendFormat": "{{component}}"
    }
   ]
  }
 ]
}